export const CATEGORIES = [
    "Bolsa para aseo",
    "Bolsa de vivero",
    "Bolsa hermetica",
    "Bolsa manija",
    "Bolsa boutique",
    "Cintas",
    "Rollo de fibra en polipropileno",
    "Rollos de plastico pólietileno negro",
    "Rollos de plastico invernadero",
    "Rollo de manila matizada",
    "Rollo de manila en polipropileno",
    "Rollo de telas de encerramiento",
    "Rollo de polisombras",
    "Rollo vinipel osmotico",
    "Rollo de vinipel industrial o stress",
    "Elementos de aseo y seguridad",
    "Lonas de empaque",
    "Vasos",
    "Platos",
    "Desechables y otros",
    "Papeleras y dispensadores",
]