export const PRODUCTS = [
  {
    name: "BOLSA TRANSPARENTE DELGADA",
    imageSrc: "/images/BolsaTransparente/bt.webp",
    category: "Bolsa transparente delgada",
    variation: [
      "5X9",
      "6X8",
      "6X11",
      "8X12",
      "9X14",
      "10X16",
      "14X20",
      "16X24",
      "20X28",
      "24X36",
    ],
  },
  {
    name: "BOLSA TRANSPARENTE GRUESA",
    imageSrc: "/images/BolsaTransparente/bt.webp",
    category: "Bolsa transparente gruesa",
    variation: [
      "5X9",
      "6X11",
      "8X12",
      "9X14",
      "10X16",
      "12X20",
      "14X20",
      "16X24",
      "20X28",
      "24X36",
      "28X44",
      "39X48",
    ],
  },
  {
    name: "BOLSA PAPELERA NEGRA 40*60CM",
    imageSrc: "/images/BolsaBasura/bb.webp",
    category: "Bolsa para aseo",
    variation: ["NEGRA", "BLANCA", "ROJA", "VERDE"],
  },
  {
    name: "BOLSA CACERA 50*70CM",
    imageSrc: "/images/BolsaCacera/bc.webp",
    category: "Bolsa para aseo",
    variation: ["NEGRA", "BLANCA", "ROJA", "VERDE"],
  },
  {
    name: "BOLSA INDUSTRIAL 60*80CM",
    imageSrc: "/images/BolsaIndustrial/bi.webp",
    category: "Bolsa para aseo",
    variation: ["NEGRA", "BLANCA", "ROJA", "VERDE"],
  },
  {
    name: "BOLSA JUMBO 70*100CM",
    imageSrc: "/images/BolsaJumbo/bj.webp",
    category: "Bolsa para aseo",
    variation: ["NEGRA", "BLANCA", "ROJA", "VERDE"],
  },
  {
    name: "BOLSA EXTRAJUMBO 80*110CM",
    imageSrc: "/images/BolsaExtrajumbo/be.webp",
    category: "Bolsa para aseo",
    variation: ["NEGRA", "BLANCA", "ROJA", "VERDE"],
  },
  {
    name: "BOLSA ESPECIAL 100*120CM",
    imageSrc: "/images/BolsaEspecial/bes.webp",
    category: "Bolsa para aseo",
    variation: ["NEGRA", "BLANCA", "ROJA", "VERDE"],
  },
  {
    name: "BOLSA DE VIVERO",
    imageSrc: "/images/BolsaVivero/bv.webp",
    category: "Bolsa de vivero",
    variation: [
      "TUBO 7X14CM",
      "10X17CM",
      "4X6",
      "5X7",
      "6X8",
      "6X11",
      "7X7",
      "8X8",
      "8X12",
      "8X16",
      "10X10",
      "12X12",
      "14X14",
      "16X16",
      "16X18",
      "24X24",
      "39X39",
    ],
  },
  {
    name: "BOLSA HERMETICA",
    imageSrc: "/images/BolsaHermetica/bh.webp",
    category: "Bolsa hermetica",
    variation: [
      "5X6CM",
      "6X9CM",
      "8X10CM",
      "10X14CM",
      "14X14CM",
      "14X18CM",
      "15X20CM",
      "18X22CM",
      "20X24CM",
      "20X30CM",
      "23X32CM",
      "25X36CM",
      "30X40CM",
      "40X40CM",
      "40X48CM",
    ],
  },
  {
    name: "BOLSA MANIJA",
    imageSrc: "/images/BolsaManija/bm_2.webp",
    category: "Bolsa manija",

    variation: [
      "No.1 1/2",
      "No.2",
      "No.3",
      "No.5",
      "No.10",
      "No.15",
      "No.20",
      "No.25",
      "No.30",
      "No.50",
    ],
  },
  {
    name: "BOLSA BOUTIQUE",
    imageSrc: "/images/BolsaBoutique/bbt_2.webp",
    category: "Bolsa boutique",
    variation: ["8X12", "9X14", "12X16", "14X20", "16X24"],
  },
  {
    name: "CINTA ADHESIVA",
    imageSrc: "/images/CintaAhdesiva/ca.webp",
    category: "Cintas",
    variation: ["100 MTRS", "200 MTRS", "300 MTRS"],
  },
  {
    name: "CINTA DE DUCTO GRIS",
    imageSrc: "/images/CintaDeDuctoGris/cd.webp",
    category: "Cintas",
    variation: ["10 MTRS", "40 MTRS"],
  },
  {
    name: "CINTA PELIGRO",
    imageSrc: "/images/CintaPeligro/cp.webp",
    category: "Cintas",
    variation: ["100 MTRS", "500 MTRS"],
  },
  {
    name: "ROLLO DE FIBRA ATAFACIL X 130 MTRS",
    imageSrc: "/images/RolloDeFibraAtafacil/rdfa.webp",
    category: "Rollo de fibra en polipropileno",
    variation: [],
  },
  {
    name: "ROLLO DE FIBRA EN POLIPROPILENO",
    imageSrc: "/images/RolloDeFibraDePolipropileno/rfp_2.webp",
    category: "Rollo de fibra en pólipropileno",
    variation: ["500 MTRS", "750 MTRS", "2000 MTRS"],
  },
  {
    name: "ROLLO DE PLASTICO NEGRO APROX CAL. 6",
    imageSrc: "/images/RollosPlastico/rp_2.webp",
    category: "Rollos de plastico pólietileno negro",
    variation: [
      "2 MTRS X 200 MTRS",
      "3 MTRS X 100 MTRS",
      "4 MTRS X 80 MTRS",
      "6 MTRS X 70 MTRS",
      "8 MTRS X 50 MTRS",
    ],
  },
  {
    name: "ROLLO DE PLASTICO NEGRO APROX CAL. 8",
    imageSrc: "/images/RollosPlastico/rp_3.webp",
    category: "Rollos de plastico pólietileno negro",
    variation: ["6 MTRS X 50 MTRS", "8 MTRS X 50 MTRS", "10 MTRS X 50 MTRS"],
  },
  {
    name: "ROLLO DE PLASTICO INVERNADERO CAL. 6",
    imageSrc: "/images/RolloInvernadero/ri.webp",
    category: "Rollos de plastico invernadero",
    variation: [
      "4 MTRS X 50 MTRS",
      "6 MTRS X 70 MTRS",
      "8 MTRS X 50 MTRS",
      "10 MTRS X 50 MTRS",
    ],
  },
  {
    name: "ROLLO DE PLASTICO INVERNADERO CAL. 8",
    imageSrc: "/images/RolloInvernadero/ri_2.webp",
    category: "Rollos de plastico invernadero",
    variation: [
      "4 MTRS X 50 MTRS",
      "6 MTRS X 50 MTRS",
      "8 MTRS X 50 MTRS",
      "10 MTRS X 50 MTRS",
    ],
  },
  {
    name: "ROLLO DE MANILA MATIZADA",
    imageSrc: "/images/RolloManillaMatizada/rmm.webp",
    category: "Rollo de manila matizada",
    variation: [
      "No.6 X 500 MTRS",
      "No.8 X 400 MTRS",
      "No.10 X  200 MTRS",
      "No.12 X 200 MTRS",
    ],
  },
  {
    name: "ROLLO DE MANILA EN POLIPROPILENO",
    imageSrc: "/images/RolloManillaPolipropileno/rmp.webp",
    category: "Rollo de manila en polipropileno",
    variation: [
      "No.3MM X 1000 MTRS",
      "No.5MM X 1000 MTRS",
      "No.6MM X 500 MTRS",
      "No.8MM X 400 MTRS",
      "No.10MM X 250 MTRS",
      "No.13MM X 200 MTRS",
    ],
  },
  {
    name: "ROLLO DE TELAS DE ENCERRAMIENTO",
    imageSrc: "/images/TelasEncerramiento/te_3.webp",
    category: "Rollo de telas de encerramiento",
    variation: [
      "VERDE DE 2X 100 MTRS",
      "NEGRA DE 2X 100 MTRS",
      "BLANCA DE 2X 100 MTRS",
      "VERDE PELIGRO DE 1X 100 MTRS",
      "VERDE CON POLISOMBRA DE 2X 100 MTRS",
    ],
  },
  {
    name: "ROLLO DE POLISOMBRAS DE 4 X 100 MTRS",
    imageSrc: "/images/RolloDePolisombra/rp_3.webp",
    category: "Rollo de polisombras",
    variation: [
      "20 MTRS",
      "50 MTRS",
      "100 MTRS",
      "200 MTRS",
      "300 MTRS",
      "500 MTRS",
      "1500 MTRS",
    ],
  },
  {
    name: "ROLLO VINIPEL OSMOTICO",
    imageSrc: "/images/RolloOsmotico/ro.webp",
    category: "Rollo vinipel osmotico",
    variation: [
      "20 MTRS",
      "50 MTRS",
      "100 MTRS",
      "200 MTRS",
      "300 MTRS",
      "500 MTRS",
      "1500 MTRS",
    ],
  },
  {
    name: "ROLLO DE VINIPEL INDUSTRIAL O STRESS",
    imageSrc: "/images/RolloVinipelIndustrialoStress/rv.webp",
    category: "Rollo de vinipel industrial o stress",
    variation: ["6 X 300 MTRS", "12 X 300 MTRS", "20 X 300 MTRS"],
  },
  {
    name: "ESCOBA SUAVE",
    imageSrc: "/images/EscobaSuave/es.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["ECONÓMICA", "DANNA"],
  },
  {
    name: "ESCOBA DURA",
    imageSrc: "/images/EscobaDura/ed.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "CEPILLO DE PISO",
    imageSrc: "/images/CepilloPiso/cp.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "CEPILLO CARRETERO",
    imageSrc: "/images/CepilloCarretero/cc.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "ARAGAN",
    imageSrc: "/images/Aragan/a.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "TELARAÑERO",
    imageSrc: "/images/Telaranero/t.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "TRAPERO",
    imageSrc: "/images/Trapero/t.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["REF. 1000", "REF. 1200"],
  },
  {
    name: "RASTRILLO",
    imageSrc: "/images/Rastrillo/r.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["METÁLICO", "PLÁSTICO"],
  },
  {
    name: "CEPILLO DE MANO",
    imageSrc: "/images/CepilloMano/cm.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "CHURRUSCO",
    imageSrc: "/images/Churrusco/c.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "CHUPA",
    imageSrc: "/images/Chupa/c.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "MOPA DE 80 CM",
    imageSrc: "/images/Mopa/m.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "RECOGEDOR",
    imageSrc: "/images/Recogedor/r.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },

  {
    name: "LIMPIAVIDRIOS",
    imageSrc: "/images/LimpiaVidrios/lv.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "LIMPION DE MANO",
    imageSrc: "/images/LimpionDeManos/lm.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "LIMPION EN MICROFIBRA",
    imageSrc: "/images/LimpionMicrofibra/lm.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "JABÓN DE MANOS",
    imageSrc: "/images/JabonDeManos/jm.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["GALÓN", "GARRAFA"],
  },
  {
    name: "LIMPIAVIDRIOS",
    imageSrc: "/images/LimpiaVidrios/lv_2.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["GALÓN", "GARRAFA"],
  },
  {
    name: "GEL ANTIBACTERIAL",
    imageSrc: "/images/GelAntibacterial/ga.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["GALÓN", "GARRAFA"],
  },
  {
    name: "JABÓN LAVALOZA",
    imageSrc: "/images/JabonLavaloza/jl.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["GALÓN", "GARRAFA"],
  },
  {
    name: "HIPOCLORITO AL 15%",
    imageSrc: "/images/Hipoclorito/h.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["GALÓN", "GARRAFA"],
  },
  {
    name: "CREOLINA",
    imageSrc: "/images/Creolina/c.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["GALÓN", "GARRAFA"],
  },
  {
    name: "DESENGRASANTE",
    imageSrc: "/images/Desengrasante/d.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["GALÓN", "GARRAFA"],
  },
  {
    name: "VARSOL",
    imageSrc: "/images/Varsol/v.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["GALÓN", "GARRAFA"],
  },
  {
    name: "AMBIENTADOR",
    imageSrc: "/images/Ambientador/a.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["GALÓN", "GARRAFA"],
  },
  {
    name: "AMONIO CUATERNARIO",
    imageSrc: "/images/Amonio/a.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["GALÓN", "GARRAFA"],
  },
  {
    name: "JABÓN EN POLVO",
    imageSrc: "/images/JabonEnPolvo/jp_2.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["KILO", "5 KLS", "BULTO"],
  },
  {
    name: "PAPEL HIGIENICO",
    imageSrc: "/images/PapelHigienico/ph_2.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["POPULAR", "SUPER BLANK", "INSTITUCIONAL"],
  },
  {
    name: "GUANTE DE ASEO NEGRO",
    imageSrc: "/images/GuantesDeAseoNegro/ga.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["CAL. 25", "CAL. 35"],
  },
  {
    name: "GUANTE DE ASEO AMARILLO",
    imageSrc: "/images/GuantesDeAseoAmarillo/gaa.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "GUANTE DE VAQUETA SENCILLO",
    imageSrc: "/images/GuanteDeVaquetaSencilloyReforzado/gvsr_2.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["SENCILLO", "REFORZADO"],
  },
  {
    name: "GUANTE PEPAS",
    imageSrc: "/images/GuantePepas/gp.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "GUANTE NITRILO",
    imageSrc: "/images/GuanteDeNitrilo/gn.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["NEGRO", "ROJO"],
  },
  {
    name: "TAPABOCAS INDUSTRIAL X 100 UNI",
    imageSrc: "/images/TapabocaIndustrial/ti.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "CAJA DE GUANTE DE NITRILO",
    imageSrc: "/images/CajaDeGuanteDeTrilo/cgt.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "CAJA DE TAPABOCAS",
    imageSrc: "/images/CajaDeTapabocas/c.webp",
    category: "Elementos de aseo y seguridad",
    variation: ["ADULTO", "NIÑO"],
  },
  {
    name: "TOALLA DE MANO EN Z X 150 UNI",
    imageSrc: "/images/ToallaManoEnZ/tmz.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "CAJA DE TOALLA DE MANO EN Z",
    imageSrc: "/images/CajaDeToallaManoEnZ/ctmz.webp",
    category: "Elementos de aseo y seguridad",
    variation: [],
  },
  {
    name: "LONAS DE EMPAQUE",
    imageSrc: "/images/LonasDeEmpaque/le.webp",
    category: "Lonas de empaque",
    variation: ["SEGUNDA", "TRINCHERA"],
  },
  {
    name: "LONA BLANCA DE  50X 70",
    imageSrc: "/images/LonaBlanca/lb.webp",
    category: "Lonas de empaque",
    variation: ["50 X 70", "60 X 80", "70 X 105"],
  },
  {
    name: "LONA ECUATORIANA ",
    imageSrc: "/images/LonasEcuatorianas/le.webp",
    category: "Lonas de empaque",
    variation: [],
  },
  {
    name: "VASO DE TINTO",
    imageSrc: "/images/VasoDeTinto/vt.webp",
    category: "Vasos",
    variation: ["PQTE", "CAJA X 60"],
  },
  {
    name: "VASO 7 OZ",
    imageSrc: "/images/Vaso7Onz/v7o.webp",
    category: "Vasos",
    variation: ["PQTE", "CAJA X 40"],
  },
  {
    name: "VASO 9 OZ",
    imageSrc: "/images/Vaso9Onz/v9o.webp",
    category: "Vasos",
    variation: ["PQTE", "CAJA X 25"],
  },
  {
    name: "VASO 14 OZ",
    imageSrc: "/images/Vaso14Onz/v14o.webp",
    category: "Vasos",
    variation: ["PQTE", "CAJA X 25"],
  },
  {
    name: "VASO DE CARTÓN",
    imageSrc: "/images/VasoCarton7Onz/vc7o.webp",
    category: "Vasos",
    variation: ["4 OZ", "7 OZ"],
  },
  {
    name: "VASO DE WHISKEY X 20 UNI",
    imageSrc: "/images/VasoWhiskhey/vw.webp",
    category: "Vasos",
    variation: [],
  },
  {
    name: "COPA AGUARDIENTERA X 50",
    imageSrc: "/images/CopaAguardientera/ca.webp",
    category: "Vasos",
    variation: [],
  },
  {
    name: "COPA DE CHAMPAÑA X 20 UNI",
    imageSrc: "/images/CopaDeChampana/cc.webp",
    category: "Vasos",
    variation: [],
  },
  {
    name: "PLATO DE TORTA 15,5 CM",
    imageSrc: "/images/PlatosDesechables/pd.webp",
    category: "Platos",
    variation: [],
  },
  {
    name: "PLATO SECO",
    imageSrc: "/images/PlatoSeco/ps.webp",
    category: "Platos",
    variation: ["20 CM", "23 CM", "26 CM"],
  },
  {
    name: "PLATO DE SOPA",
    imageSrc: "/images/PlatoSopa/ps.webp",
    category: "Platos",
    variation: [],
  },
  {
    name: "CONTENEDOR J-1",
    imageSrc: "/images/ContenedorJ-1/cj1.webp",
    category: "Desechables y otros",
    variation: ["X 20", "X 200"],
  },
  {
    name: "CONTENEDOR 16 OZ",
    imageSrc: "/images/Contenedor16Oz/c16o.webp",
    category: "Desechables y otros",
    variation: ["16 OZ", "24 OZ"],
  },
  {
    name: "CUCHARA X 100",
    imageSrc: "/images/CucharaDesechable/cd.webp",
    category: "Desechables y otros",
    variation: ["GRANDE", "PQÑA"],
  },
  {
    name: "TENEDOR X 100",
    imageSrc: "/images/TenedorDesechable/td.webp",
    category: "Desechables y otros",
    variation: ["GRANDE", "PQÑO"],
  },
  {
    name: "CUCHILLO X 100",
    imageSrc: "/images/CuchilloDesechable/cd.webp",
    category: "Desechables y otros",
    variation: [],
  },
  {
    name: "PUNTO ECOLOGICO DE 3 PUESTOS",
    imageSrc: "/images/PuntosEcologicos/pe.webp",
    category: "Papeleras y dispensadores",
    variation: ["3 PUESTOS", "4 PUESTOS"],
  },
  {
    name: "CANECA PAPELERA DE PEDAL",
    imageSrc: "/images/CanecaPapeleraPedal/cpp.webp",
    category: "Papeleras y dispensadores",
    variation: [
      "9 LTRS (VERDE, BLANCA NEGRA ROJA)",
      "12 LTRS (VERDE, BLANCA NEGRA ROJA)",
      "21 LTRS (VERDE, BLANCA NEGRA ROJA)",
      "25 LTRS (VERDE, BLANCA NEGRA ROJA)",
      "60 LTRS (VERDE, BLANCA NEGRA ROJA)",
    ],
  },
  {
    name: "CANECA PAPELERA VAIVEN",
    imageSrc: "/images/CanecaVaiven/cv.webp",
    category: "Papeleras y dispensadores",
    variation: [
      "5 LTRS (VERDE, BLANCA, NEGRA, ROJA)",
      "10 LTRS (VERDE, BLANCA, NEGRA, ROJA)",
      "14 LTRS (VERDE, BLANCA, NEGRA, ROJA",
      "25 LTRS (VERDE, BLANCA, NEGRA, ROJA",
      "36 LTRS (VERDE, BLANCA, NEGRA, ROJA",
      "55 LTRS (VERDE, BLANCA, NEGRA, ROJA",
    ],
  },
  {
    name: "TANQUE",
    imageSrc: "/images/Tanque/t.webp",
    category: "Papeleras y dispensadores",
    variation: [
      "30 LTRS",
      "50 LTRS",
      "65 LTRS",
      "80 LTRS",
      "110 LTRS",
      "120 LTRS",
      "160 LTRS",
    ],
  },
  {
    name: "VALDE ECO",
    imageSrc: "/images/ValdeEco/ve.webp",
    category: "Papeleras y dispensadores",
    variation: [],
  },
  {
    name: "VALDE DE 12 LTRS IMUSA",
    imageSrc: "/images/ValdeImusa/vi.webp",
    category: "Papeleras y dispensadores",
    variation: [],
  },
  {
    name: "ESCURRIDOR DE TRAPERO",
    imageSrc: "/images/EscurridorTrapero/et.webp",
    category: "Papeleras y dispensadores",
    variation: [],
  },
  {
    name: "DISPENSADOR DE JABON DE PARED",
    imageSrc: "/images/DispensadorDeParedDeJabonDeManos/dpjm.webp",
    category: "Papeleras y dispensadores",
    variation: [],
  },
  {
    name: "DISPENSADOR DE PAPEL INSTITUCIONAL",
    imageSrc: "/images/DispensadorDePapelInstitucional/dpi.webp",
    category: "Papeleras y dispensadores",
    variation: [],
  },
  {
    name: "DISPENSADOR DE TOALLA EN Z",
    imageSrc: "/images/ToallaDeMano/tm.webp",
    category: "Papeleras y dispensadores",
    variation: [],
  },
];
